// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: snakes.proto

package ru.levachev.messages;

public interface GamePlayersOrBuilder extends
    // @@protoc_insertion_point(interface_extends:snakes.GamePlayers)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Список всех игроков
   * </pre>
   *
   * <code>repeated .snakes.GamePlayer players = 1;</code>
   */
  java.util.List<GamePlayer>
      getPlayersList();
  /**
   * <pre>
   * Список всех игроков
   * </pre>
   *
   * <code>repeated .snakes.GamePlayer players = 1;</code>
   */
  GamePlayer getPlayers(int index);
  /**
   * <pre>
   * Список всех игроков
   * </pre>
   *
   * <code>repeated .snakes.GamePlayer players = 1;</code>
   */
  int getPlayersCount();
  /**
   * <pre>
   * Список всех игроков
   * </pre>
   *
   * <code>repeated .snakes.GamePlayer players = 1;</code>
   */
  java.util.List<? extends GamePlayerOrBuilder>
      getPlayersOrBuilderList();
  /**
   * <pre>
   * Список всех игроков
   * </pre>
   *
   * <code>repeated .snakes.GamePlayer players = 1;</code>
   */
  GamePlayerOrBuilder getPlayersOrBuilder(
      int index);
}
