// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: snakes.proto

package ru.levachev.messages;

public interface GameAnnouncementOrBuilder extends
    // @@protoc_insertion_point(interface_extends:snakes.GameAnnouncement)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Текущие игроки
   * </pre>
   *
   * <code>required .snakes.GamePlayers players = 1;</code>
   * @return Whether the players field is set.
   */
  boolean hasPlayers();
  /**
   * <pre>
   * Текущие игроки
   * </pre>
   *
   * <code>required .snakes.GamePlayers players = 1;</code>
   * @return The players.
   */
  GamePlayers getPlayers();
  /**
   * <pre>
   * Текущие игроки
   * </pre>
   *
   * <code>required .snakes.GamePlayers players = 1;</code>
   */
  GamePlayersOrBuilder getPlayersOrBuilder();

  /**
   * <pre>
   * Параметры игры
   * </pre>
   *
   * <code>required .snakes.GameConfig config = 2;</code>
   * @return Whether the config field is set.
   */
  boolean hasConfig();
  /**
   * <pre>
   * Параметры игры
   * </pre>
   *
   * <code>required .snakes.GameConfig config = 2;</code>
   * @return The config.
   */
  GameConfig getConfig();
  /**
   * <pre>
   * Параметры игры
   * </pre>
   *
   * <code>required .snakes.GameConfig config = 2;</code>
   */
  GameConfigOrBuilder getConfigOrBuilder();

  /**
   * <pre>
   * Можно ли новому игроку присоединиться к игре (есть ли место на поле)
   * </pre>
   *
   * <code>optional bool can_join = 3 [default = true];</code>
   * @return Whether the canJoin field is set.
   */
  boolean hasCanJoin();
  /**
   * <pre>
   * Можно ли новому игроку присоединиться к игре (есть ли место на поле)
   * </pre>
   *
   * <code>optional bool can_join = 3 [default = true];</code>
   * @return The canJoin.
   */
  boolean getCanJoin();

  /**
   * <pre>
   * Глобально уникальное имя игры, например "my game"
   * </pre>
   *
   * <code>required string game_name = 4;</code>
   * @return Whether the gameName field is set.
   */
  boolean hasGameName();
  /**
   * <pre>
   * Глобально уникальное имя игры, например "my game"
   * </pre>
   *
   * <code>required string game_name = 4;</code>
   * @return The gameName.
   */
  String getGameName();
  /**
   * <pre>
   * Глобально уникальное имя игры, например "my game"
   * </pre>
   *
   * <code>required string game_name = 4;</code>
   * @return The bytes for gameName.
   */
  com.google.protobuf.ByteString
      getGameNameBytes();
}
