// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: snakes.proto

package ru.levachev.messages;

public final class Snakes {
  private Snakes() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_snakes_GamePlayer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_snakes_GamePlayer_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_snakes_GameConfig_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_snakes_GameConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_snakes_GamePlayers_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_snakes_GamePlayers_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_snakes_GameState_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_snakes_GameState_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_snakes_GameState_Coord_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_snakes_GameState_Coord_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_snakes_GameState_Snake_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_snakes_GameState_Snake_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_snakes_GameAnnouncement_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_snakes_GameAnnouncement_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_snakes_GameMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_snakes_GameMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_snakes_GameMessage_PingMsg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_snakes_GameMessage_PingMsg_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_snakes_GameMessage_SteerMsg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_snakes_GameMessage_SteerMsg_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_snakes_GameMessage_AckMsg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_snakes_GameMessage_AckMsg_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_snakes_GameMessage_StateMsg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_snakes_GameMessage_StateMsg_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_snakes_GameMessage_AnnouncementMsg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_snakes_GameMessage_AnnouncementMsg_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_snakes_GameMessage_DiscoverMsg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_snakes_GameMessage_DiscoverMsg_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_snakes_GameMessage_JoinMsg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_snakes_GameMessage_JoinMsg_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_snakes_GameMessage_ErrorMsg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_snakes_GameMessage_ErrorMsg_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_snakes_GameMessage_RoleChangeMsg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_snakes_GameMessage_RoleChangeMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\014snakes.proto\022\006snakes\"\240\001\n\nGamePlayer\022\014\n" +
      "\004name\030\001 \002(\t\022\n\n\002id\030\002 \002(\005\022\022\n\nip_address\030\003 " +
      "\001(\t\022\014\n\004port\030\004 \001(\005\022\036\n\004role\030\005 \002(\0162\020.snakes" +
      ".NodeRole\022\'\n\004type\030\006 \001(\0162\022.snakes.PlayerT" +
      "ype:\005HUMAN\022\r\n\005score\030\007 \002(\005\"i\n\nGameConfig\022" +
      "\021\n\005width\030\001 \001(\005:\00240\022\022\n\006height\030\002 \001(\005:\00230\022\026" +
      "\n\013food_static\030\003 \001(\005:\0011\022\034\n\016state_delay_ms" +
      "\030\005 \001(\005:\0041000\"2\n\013GamePlayers\022#\n\007players\030\001" +
      " \003(\0132\022.snakes.GamePlayer\"\214\003\n\tGameState\022\023" +
      "\n\013state_order\030\001 \002(\005\022\'\n\006snakes\030\002 \003(\0132\027.sn" +
      "akes.GameState.Snake\022&\n\005foods\030\003 \003(\0132\027.sn" +
      "akes.GameState.Coord\022$\n\007players\030\004 \002(\0132\023." +
      "snakes.GamePlayers\032#\n\005Coord\022\014\n\001x\030\001 \001(\021:\001" +
      "0\022\014\n\001y\030\002 \001(\021:\0010\032\315\001\n\005Snake\022\021\n\tplayer_id\030\001" +
      " \002(\005\022\'\n\006points\030\002 \003(\0132\027.snakes.GameState." +
      "Coord\0228\n\005state\030\003 \002(\0162\".snakes.GameState." +
      "Snake.SnakeState:\005ALIVE\022)\n\016head_directio" +
      "n\030\004 \002(\0162\021.snakes.Direction\"#\n\nSnakeState" +
      "\022\t\n\005ALIVE\020\000\022\n\n\006ZOMBIE\020\001\"\207\001\n\020GameAnnounce" +
      "ment\022$\n\007players\030\001 \002(\0132\023.snakes.GamePlaye" +
      "rs\022\"\n\006config\030\002 \002(\0132\022.snakes.GameConfig\022\026" +
      "\n\010can_join\030\003 \001(\010:\004true\022\021\n\tgame_name\030\004 \002(" +
      "\t\"\336\007\n\013GameMessage\022\017\n\007msg_seq\030\001 \002(\003\022\021\n\tse" +
      "nder_id\030\n \001(\005\022\023\n\013receiver_id\030\013 \001(\005\022+\n\004pi" +
      "ng\030\002 \001(\0132\033.snakes.GameMessage.PingMsgH\000\022" +
      "-\n\005steer\030\003 \001(\0132\034.snakes.GameMessage.Stee" +
      "rMsgH\000\022)\n\003ack\030\004 \001(\0132\032.snakes.GameMessage" +
      ".AckMsgH\000\022-\n\005state\030\005 \001(\0132\034.snakes.GameMe" +
      "ssage.StateMsgH\000\022;\n\014announcement\030\006 \001(\0132#" +
      ".snakes.GameMessage.AnnouncementMsgH\000\022+\n" +
      "\004join\030\007 \001(\0132\033.snakes.GameMessage.JoinMsg" +
      "H\000\022-\n\005error\030\010 \001(\0132\034.snakes.GameMessage.E" +
      "rrorMsgH\000\0228\n\013role_change\030\t \001(\0132!.snakes." +
      "GameMessage.RoleChangeMsgH\000\0223\n\010discover\030" +
      "\014 \001(\0132\037.snakes.GameMessage.DiscoverMsgH\000" +
      "\032\t\n\007PingMsg\0320\n\010SteerMsg\022$\n\tdirection\030\001 \002" +
      "(\0162\021.snakes.Direction\032\010\n\006AckMsg\032,\n\010State" +
      "Msg\022 \n\005state\030\001 \002(\0132\021.snakes.GameState\032:\n" +
      "\017AnnouncementMsg\022\'\n\005games\030\001 \003(\0132\030.snakes" +
      ".GameAnnouncement\032\r\n\013DiscoverMsg\032\213\001\n\007Joi" +
      "nMsg\022.\n\013player_type\030\001 \001(\0162\022.snakes.Playe" +
      "rType:\005HUMAN\022\023\n\013player_name\030\003 \002(\t\022\021\n\tgam" +
      "e_name\030\004 \002(\t\022(\n\016requested_role\030\005 \002(\0162\020.s" +
      "nakes.NodeRole\032!\n\010ErrorMsg\022\025\n\rerror_mess" +
      "age\030\001 \002(\t\032_\n\rRoleChangeMsg\022%\n\013sender_rol" +
      "e\030\001 \001(\0162\020.snakes.NodeRole\022\'\n\rreceiver_ro" +
      "le\030\002 \001(\0162\020.snakes.NodeRoleB\006\n\004Type*:\n\010No" +
      "deRole\022\n\n\006NORMAL\020\000\022\n\n\006MASTER\020\001\022\n\n\006DEPUTY" +
      "\020\002\022\n\n\006VIEWER\020\003*\"\n\nPlayerType\022\t\n\005HUMAN\020\000\022" +
      "\t\n\005ROBOT\020\001*2\n\tDirection\022\006\n\002UP\020\001\022\010\n\004DOWN\020" +
      "\002\022\010\n\004LEFT\020\003\022\t\n\005RIGHT\020\004B\030\n\024ru.levachev.me" +
      "ssagesP\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_snakes_GamePlayer_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_snakes_GamePlayer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_snakes_GamePlayer_descriptor,
        new String[] { "Name", "Id", "IpAddress", "Port", "Role", "Type", "Score", });
    internal_static_snakes_GameConfig_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_snakes_GameConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_snakes_GameConfig_descriptor,
        new String[] { "Width", "Height", "FoodStatic", "StateDelayMs", });
    internal_static_snakes_GamePlayers_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_snakes_GamePlayers_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_snakes_GamePlayers_descriptor,
        new String[] { "Players", });
    internal_static_snakes_GameState_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_snakes_GameState_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_snakes_GameState_descriptor,
        new String[] { "StateOrder", "Snakes", "Foods", "Players", });
    internal_static_snakes_GameState_Coord_descriptor =
      internal_static_snakes_GameState_descriptor.getNestedTypes().get(0);
    internal_static_snakes_GameState_Coord_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_snakes_GameState_Coord_descriptor,
        new String[] { "X", "Y", });
    internal_static_snakes_GameState_Snake_descriptor =
      internal_static_snakes_GameState_descriptor.getNestedTypes().get(1);
    internal_static_snakes_GameState_Snake_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_snakes_GameState_Snake_descriptor,
        new String[] { "PlayerId", "Points", "State", "HeadDirection", });
    internal_static_snakes_GameAnnouncement_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_snakes_GameAnnouncement_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_snakes_GameAnnouncement_descriptor,
        new String[] { "Players", "Config", "CanJoin", "GameName", });
    internal_static_snakes_GameMessage_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_snakes_GameMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_snakes_GameMessage_descriptor,
        new String[] { "MsgSeq", "SenderId", "ReceiverId", "Ping", "Steer", "Ack", "State", "Announcement", "Join", "Error", "RoleChange", "Discover", "Type", });
    internal_static_snakes_GameMessage_PingMsg_descriptor =
      internal_static_snakes_GameMessage_descriptor.getNestedTypes().get(0);
    internal_static_snakes_GameMessage_PingMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_snakes_GameMessage_PingMsg_descriptor,
        new String[] { });
    internal_static_snakes_GameMessage_SteerMsg_descriptor =
      internal_static_snakes_GameMessage_descriptor.getNestedTypes().get(1);
    internal_static_snakes_GameMessage_SteerMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_snakes_GameMessage_SteerMsg_descriptor,
        new String[] { "Direction", });
    internal_static_snakes_GameMessage_AckMsg_descriptor =
      internal_static_snakes_GameMessage_descriptor.getNestedTypes().get(2);
    internal_static_snakes_GameMessage_AckMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_snakes_GameMessage_AckMsg_descriptor,
        new String[] { });
    internal_static_snakes_GameMessage_StateMsg_descriptor =
      internal_static_snakes_GameMessage_descriptor.getNestedTypes().get(3);
    internal_static_snakes_GameMessage_StateMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_snakes_GameMessage_StateMsg_descriptor,
        new String[] { "State", });
    internal_static_snakes_GameMessage_AnnouncementMsg_descriptor =
      internal_static_snakes_GameMessage_descriptor.getNestedTypes().get(4);
    internal_static_snakes_GameMessage_AnnouncementMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_snakes_GameMessage_AnnouncementMsg_descriptor,
        new String[] { "Games", });
    internal_static_snakes_GameMessage_DiscoverMsg_descriptor =
      internal_static_snakes_GameMessage_descriptor.getNestedTypes().get(5);
    internal_static_snakes_GameMessage_DiscoverMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_snakes_GameMessage_DiscoverMsg_descriptor,
        new String[] { });
    internal_static_snakes_GameMessage_JoinMsg_descriptor =
      internal_static_snakes_GameMessage_descriptor.getNestedTypes().get(6);
    internal_static_snakes_GameMessage_JoinMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_snakes_GameMessage_JoinMsg_descriptor,
        new String[] { "PlayerType", "PlayerName", "GameName", "RequestedRole", });
    internal_static_snakes_GameMessage_ErrorMsg_descriptor =
      internal_static_snakes_GameMessage_descriptor.getNestedTypes().get(7);
    internal_static_snakes_GameMessage_ErrorMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_snakes_GameMessage_ErrorMsg_descriptor,
        new String[] { "ErrorMessage", });
    internal_static_snakes_GameMessage_RoleChangeMsg_descriptor =
      internal_static_snakes_GameMessage_descriptor.getNestedTypes().get(8);
    internal_static_snakes_GameMessage_RoleChangeMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_snakes_GameMessage_RoleChangeMsg_descriptor,
        new String[] { "SenderRole", "ReceiverRole", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
